book/Zapp-Pipes/5.-Feed-API.md
book/dev-env/iOS.md
book/getting-started/ios-podspec.md

This PR adds documentation regarding hosting pod specs and versioning handling in iOS

Dependancy versioning

---

book/SUMMARY.md
book/dev-env/iOS.md
book/dev-env/iOS/download-development-project.md
book/dev-env/iOS/utils.md
book/plugins-guidelines/plugin_submission_guideline.md

* Added documentation for Zapp App connector
* Slightly revised the structure of the getting started in iOS to make more sense order wise and include the connector documentation

App connector

---

book/SUMMARY.md
book/getting-started/communication-between-plugins.md

Session and Local Storage Documentation WIP

Session and Local Storage Documentation

---

book/zappifest/plugins-manifest-format.md

This PR adds a new option documentation for `targets ` and `max_items_per_type `

feat(manifest options): adds a new option documentation

---

book/plugins/general-abilities/communication-between-plugins/communication-between-plugins.md

Updating the documentation regarding the communication between plugins. Like in iOS, in Android there is a class now named `SessionStorageUtil`.
N/A

update(com-between-plug): updating documentation

---

book/README.md
book/SUMMARY.md
book/getting-started/zapp-plugins.md

- Improving the introduction and getting started pages in order to make it more clear to a new user.
- Removing unnecessary link to the `public plugin guidelines` in the menu.
nope.

refac(*): improving the introduction and getting started pages

---

book/getting-started/download-development-project.md

Added a few notes to be more accurate in working with Android dev project.

refactor(*): update development project section for android to more accurate.

---

book/push/push-general.md

fixing links on the push general screen

fix(push): fixing links on the push general screen

---

.pullapprove.yml

Adding pull approve github app.

adding pull approve

---

.pullapprove.yml

fixing pullapprove.yml team typo

---

.pullapprove.yml

 fixing pullapprove.yml team error

---

book/quick-brick/Api-documentation.md
book/quick-brick/Beta-guidelines.md
book/quick-brick/Setup.md

- Well, the title says it all ^
- Also updated the relevant npm badges along the way, so they match this: https://github.com/applicaster/QuickBrick/blob/master/README.md

chores(quickbrick): update last broken links since repo was renamed

---

book/dev-env/iOS.md
book/quick-brick/tvOS/Plugins/Video/VideoPluginsHowCreate.md

Added versions of tools to be used with 12.0 and up vs older Zapp iOS SDKs

feat(Intro iOS): Add version changes of tooling for Zapp SDK 12.0 and up vs older

---

book/plugins/android/single-bundle.md

fixing path to migration guide
previous path did not exist

Fix path to migration guide

---

book/dev-env/react-native.md

Updated React and React-native versions that are currently supported by our platform.
Looks like we need a different template for documentation PR's :D

chore(react-native): update version requirements

---

book/plugins/general-abilities/communication-between-plugins/communication-between-plugins.md

This PR fixes the documentation for the zapp pipes bridge documentation by adding missing methods

fix: adding missing methods in zapp pipes bridge documentation

---

book/SUMMARY.md
book/error-monitoring/error-monitoring-android.md
book/error-monitoring/error-monitoring-general.md
book/error-monitoring/error-monitoring-ios.md
book/getting-started/plugin-types.md
book/whats_new/whats_new.md

Addition of error monitoring plugin

Addition of error monitoring plugin

---

book/whats_new/20191124-swift-5.1-migration.md

chore(*): add more information for swift 5.1 migration

---

book/whats_new/20191124-swift-5.1-migration.md

fix(swift-5.1): add notes for swift 5.1 migration

---

book/SUMMARY.md
book/plugins/general-abilities/refresh-and-navigation/refresh-and-navigation.md
book/whats_new/20191124-swift-5.1-migration.md

Add new docs about navigation and refresh mechanism 

feature: add new docs about navigation and refresh mechanism 

---

book/plugins/general-abilities/refresh-and-navigation/refresh-and-navigation.md

Add minor changes to the navigation and refresh doc

fix(navigation+refresh): add alex.d p.r notes

---

book/getting-started/plugin-types.md
book/getting-started/zapp-plugins.md
book/plugins-guidelines/plugin_submission_guideline.md
book/whats_new/20190818-swift-5.0-migration.md
book/whats_new/20191124-swift-5.1-migration.md

`Dependancy` is an archaic form that doesn't sound idiomatic. The common spelling is `dependency`. IMHO it is important because it's on the first page. Other minor spelling fixes and improvements.
None
* required test cases: Proofreading
* specific apps / plugins to test : None

Improvement(Getting Started): Launguage improvements

---

book/screen/ios/screen-plugin-ios.md

There were no references to Zapp-iOS SDK before version 13.0.0, so I improved the language and formatting.

Improvement(*): Language and formatting improvements

---

book/contact_us/help_desk.md

add new technical support ticket instructions

feature(help_desk): add new technical support ticket instructions

---

book/plugins/android/single-bundle.md
book/react-native/android/android.md
book/react-native/android/debugging.md
book/react-native/android/running-on-device.md
book/react-native/intro.md
book/react-native/starter-project.md

Language improvements in the React Native plugins section. Mainly grammar and spelling.
None.
N/A
* required test cases: Read the documentation

Improvement(RN plugins): Language improvements

---

book/Zapp-Pipes/Home.md

Language improvements.
None.
* required test cases: Read the documentation.

Improvement(DSP) Home page language improvements

---

book/Zapp-Pipes/0.-Prerequisites.md
book/Zapp-Pipes/1.-Set-up.md
book/Zapp-Pipes/2.-Provider-structure.md
book/Zapp-Pipes/3.-Native-bridge-API.md
book/Zapp-Pipes/5.-Feed-API.md

Language and style improvements.
None.
* required test cases: Read the documentation.
* specific apps / plugins to test : N/A.

Improvement(DSP prerequisites): Language and grammar improvements

---

book/SUMMARY.md
book/plugins/general-abilities/url-schemes/url-schemes.md

New page about URL schemes and plugins.
None.
Open the web site.
* required test cases: Read the documentation.

New(Plugin URL schemes): New page about how to use URL schemes with plugins

---

book/Zapp-Pipes/provider-stepbystep.md

Language and grammar improvements.
None.
* required test cases: Read the website

Improvement(DSP step by step): Language and grammar improvements

---

book/dev-env/node.md

this PR updates node.js version requirements, as node 8 as ended its maintenance, and our repos are compatible with node 12 (quick brick, zapp-pipes)

chore: update node.js environment requirements

---

book/zappifest/plugins-manifest-format.md

This PR adds documentation for additional fonts_selectors

feat(fonts_selector): adds additional platforms

---

book/getting-started/download-development-project.md

New PR to force a redeploy, plus adding an example of a local pod path.

fix(download_development_project): Adding local path example

---

book/quick-brick/Setup.md

This PR is updating:
- iOS project name
- Xcode version
- Node Version

chore(QB base): updated iOS project names and Node Version

---

book/zappifest/zappifest.md

Reverts applicaster/developer.applicaster.com#351

Revert "Update zappifest.md"

---

book/zappifest/zappifest.md

Omerweiss patch 1

---

book/whats_new/20200119_plugiun_accounts.md
book/zappifest/zappifest.md

chore(zappifest): add account param

---

book/SUMMARY.md

fix(whats-new): wrong url on the summary.md for plugin account

---

book/partner-resources/overview.md

2-24-20 Incorporate Avi's Feedback

---

book/SUMMARY.md
book/ui-components/ui-component-characteristics.md
book/ui-components/ui-component-general.md
book/zappifest/plugins-manifest-format.md

- New field added to zappifest: `characteristics`
- Full explanation + examples of various possible configurations

feat(ui component): add characteristics field and examples

---

book/SUMMARY.md
book/Zapp-Pipes/11.1-dsp-search-handler.md

Add DSP search handler docs
N/A

doc(add DSP search handler)

---

book/SUMMARY.md
book/Zapp-Pipes/13.-single-channel-epg-feeds.md

Guide  for a single channel EPG on QB feeds
N/A
* [] Tests are included 
* [] This PR is making a UI change
* [] Screenshot(s) included
* required test cases: N/A

Guide  for a single channel EPG on QB feeds
